#!/bin/bash
#
# description:  metadatamanager start cmd
#
# Modified for Linkis 1.0.0


export SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-metadatamanager"

#export DEBUG_PORT=

export SERVER_CLASS=org.apache.linkis.metadatamanager.server.LinkisMetadataManagerApplication

export COMMON_START_BIN=$LINKIS_HOME/sbin/ext/linkis-common-start
if [[ ! -f "${COMMON_START_BIN}" ]]; then
    echo "The $COMMON_START_BIN  does not exist!"
    exit 1
else
    sh $COMMON_START_BIN
fi