#!/bin/bash
#
# description:  metadatamanager start cmd
# @author:      davidhua
# @created:     12.11.2021
#
# Modified for Linkis 1.0.0

source $LINKIS_CONF_DIR/linkis-env.sh

SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-metadatamanager"


export SERVER_CLASS=org.apache.linkis.metadatamanager.server.LinkisMetadataManagerApplication
export LINKIS_LOG_DIR=$LINKIS_HOME/logs
if test -z "$SERVER_HEAP_SIZE"
then
  export SERVER_HEAP_SIZE="512M"
fi

if [ "$DEBUG_PORT" ];
then
   export DEBUG_CMD="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$DEBUG_PORT"
fi

if test -z "$SERVER_JAVA_OPTS"
then
  export SERVER_JAVA_OPTS=" -DserviceName=$SERVER_NAME -Xmx$SERVER_HEAP_SIZE -XX:+UseG1GC -Xloggc:$LINKIS_LOG_DIR/${SERVER_NAME}-gc.log $DEBUG_CMD "
fi

## conf dir
export SERVER_CONF_PATH=$LINKIS_CONF_DIR

## commons lib
export LINKIS_COMMONS_LIB=$LINKIS_HOME/$LINKIS_PUBLIC_MODULE
if [ ! -r "$LINKIS_COMMONS_LIB" ] ; then
    echo "linkis commons lib not exists $LINKIS_COMMONS_LIB"
    exit 1
fi

## server lib
export SERVER_LIB=$LINKIS_HOME/lib/$SERVER_SUFFIX
if [ ! -r "$SERVER_LIB" ] ; then
    echo "server lib not exists $SERVER_LIB"
    exit 1
fi
# set the wds.linkis.server.mdm.service.lib.dir to ${SERVER_LIB}/service
SERVER_JAVA_OPTS=" -Dwds.linkis.server.mdm.service.lib.dir=${SERVER_LIB}/service"${SERVER_JAVA_OPTS}

## set class path
export SERVER_CLASS_PATH=$SERVER_CONF_PATH:$LINKIS_COMMONS_LIB/*:$SERVER_LIB/*

nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &

pid=$!
sleep 2
if [[ -z "${pid}" ]]; then
    echo "server $SERVER_NAME start failed!"
    exit 1
else
    echo "server $SERVER_NAME start succeeded!"
    echo $pid > $SERVER_PID
fi
