#!/bin/bash
#
# description:  datasourcemanager start cmd
#
# Modified for Linkis 1.0.0


export SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-datasourcesmanager"

#export DEBUG_PORT=

export SERVER_CLASS=com.webank.wedatasphere.linkis.datasourcemanager.core.LinkisDataSourceManagerApplication

export COMMON_START_BIN=$LINKIS_HOME/sbin/ext/linkis-common-start
if [[ ! -f "${COMMON_START_BIN}" ]]; then
    echo "The $COMMON_START_BIN  does not exist!"
    exit 1
else
    sh $COMMON_START_BIN
fi