#!/bin/bash
#
# description:  publicservice start cmd
# @author:      peacewong
# @created:     01.16.2021
#
# Modified for Linkis 1.0.0


export SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-publicservice"


#export DEBUG_PORT=

export SERVER_CLASS=com.webank.wedatasphere.linkis.jobhistory.LinkisPublicServiceApp

export COMMON_START_BIN=$LINKIS_HOME/sbin/ext/linkis-common-start
if [[ ! -f "${COMMON_START_BIN}" ]]; then
    echo "The $COMMON_START_BIN  does not exist!"
    exit 1
else
    sh $COMMON_START_BIN
fi