#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# description:  monitor start cmd
#


source $LINKIS_CONF_DIR/linkis-env.sh
export SERVER_SUFFIX="linkis-extensions/linkis-et-monitor"

export SERVER_CLASS=org.apache.linkis.monitor.LinksMonitorApplication

if test -z "$MONITOR_HEAP_SIZE"
  then
  if test -z "$SERVER_HEAP_SIZE"
  then
    export SERVER_HEAP_SIZE="512M"
  fi
else
  export SERVER_HEAP_SIZE=$MONITOR_HEAP_SIZE
fi

#export DEBUG_PORT=

export COMMON_START_BIN=$LINKIS_HOME/sbin/ext/linkis-common-start
if [[ ! -f "${COMMON_START_BIN}" ]]; then
    echo "The $COMMON_START_BIN  does not exist!"
    exit 1
else
    sh $COMMON_START_BIN
fi